# Generated by Django 3.2.15 on 2022-12-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='descripcion')),
            ],
        ),
        migrations.AddField(
            model_name='incidente',
            name='estado_actual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='incidentes.estado_actual'),
        ),
    ]
