from debian10

RUN apt update && apt upgrade
RUN apt install build-essential libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev libjpeg-dev zlib1g-dev
RUN apt-get install python3-pip -y
RUN pip3 install -r requirements.txt
WORKDIR /app