version: '3.3'

services:
  mapariesgos:
    container_name: mapariesgos
    depends_on:
      - db
    image: corverita/mapariesgos
    ports:
      - 80:80
      # host : invitado
    restart: always

  db:
    container_name: mapariesgos-bd
    image: corverita/mapariesgos-bd
    ports:
      - 3320:3306
    restart: always


    # Tras el encendido del compose hacer lo siguiente:

    # Entrar en el contenedor de mapariesgos y cambiar el settings
      # docker exec -it mapariesgos bash
      # cd mapariesgos
      # mv settings_prod.py settings.py         (Tambien cambiar el debug a False)
      # python3 manage.py migrate

    # Crear el superusuario
      # python3 manage.py createsuperuser
    
    # Entrar en el contenedor de la base de datos y correr el script de municipios y estados
      # docker exec -it mapariesgos-bd bash
      # mysql -u root -p < /tmp/script_estados.sql