from debian

RUN apt update
RUN apt-get install build-essential libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev libjpeg-dev zlib1g-dev apache2 libapache2-mod-wsgi-py3 python3-dev python3-pip openssh-client libmariadb-dev -y

WORKDIR /app

COPY ./mapariesgos/ /app/

COPY ./mapariesgos.conf /etc/apache2/sites-available/mapariesgos.conf

RUN a2ensite mapariesgos.conf

RUN pip3 install -r requirements.txt

RUN python3 manage.py collectstatic

RUN python3 manage.py makemigrations
RUN python3 manage.py migrate

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]